parameters:
#    cerad_org.example.class: Cerad\Bundle\OrgBundle\Example

services:
#    cerad_org.example:
#        class: %cerad_org.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
