parameters:
  
services:
  
  # ====================================================
  # Update Game Report
  cerad_game__project__game_report__update__model_factory:
        class: Cerad\Bundle\GameBundle\Action\Project\GameReport\Update\GameReportUpdateModel
        calls:
             - [setDispatcher,['@event_dispatcher']]
        arguments:
            - '@cerad_game__game_repository'
           #- '@cerad_game__game_field__repository'
            
  cerad_game__project__game_report__update__form_factory:
        class: Cerad\Bundle\GameBundle\Action\Project\GameReport\Update\GameReportUpdateFormFactory
        calls:
             - [setRouter,      ['@router']]
             - [setFormFactory, ['@form.factory']]
             
  cerad_game__project__game_report__update__controller:
        class: Cerad\Bundle\GameBundle\Action\Project\GameReport\Update\GameReportUpdateController
        calls:
             - [setRouter,     ['@router']]
             - [setTemplating, ['@templating']]
            
  # ====================================================
  # Update Game 
  cerad_game__project__game__update__by_scorer__model_factory:
        class: Cerad\Bundle\GameBundle\Action\Project\Game\Update\ByScorer\GameUpdateByScorerModel
        calls:
             - [setDispatcher,['@event_dispatcher']]
        arguments:
            - '@cerad_game__game_repository'
           #- '@cerad_game__game_field__repository'
            
  cerad_game__project__game__update__by_scorer__form_factory:
        class: Cerad\Bundle\GameBundle\Action\Project\Game\Update\ByScorer\GameUpdateByScorerFormFactory
        calls:
             - [setRouter,      ['@router']]
             - [setFormFactory, ['@form.factory']]
             
  cerad_game__project__game__update__by_scorer__controller:
        class: Cerad\Bundle\GameBundle\Action\Project\Game\Update\ByScorer\GameUpdateByScorerController
        calls:
             - [setRouter,     ['@router']]
             - [setTemplating, ['@templating']]
            
# =======================================================================
# Action: RefereeScheduleShow
#
  cerad_game__project__referee_schedule__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\RefereeSchedule\Show\RefereeScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'

  cerad_game__project__referee_schedule__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\RefereeSchedule\Show\RefereeScheduleShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__referee_schedule__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\RefereeSchedule\Show\RefereeScheduleShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
# =======================================================================
# Action: ScheduleTeamShow
#
  cerad_game__project__schedule_team__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - '@cerad_game__team_repository'

  cerad_game__project__schedule_team__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setDispatcher,  ['@event_dispatcher']]
      - [setFormFactory, ['@form.factory']]
             
  cerad_game__project__schedule_team__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
