parameters:
  cerad_game__project__results__export_xls__class: 
    Cerad\Bundle\GameBundle\Action\Project\Results\Export\ResultsExportXLS
    
  cerad_game__project__results__natgames__class: 
    Cerad\Bundle\GameBundle\Service\Results\NatGamesResults
    
services:
  # Poolplay Results calculator
  cerad_game__results_natgames:
    class: '%cerad_game__project__results__natgames__class%'
    scope: prototype
    
  cerad_game__results_s1games:
    class: Cerad\Bundle\GameBundle\Service\Results\S1GamesResults
    scope: prototype
    
  cerad_game__results_s5games:
    class: Cerad\Bundle\GameBundle\Service\Results\S5GamesResults
    scope: prototype
    
  # ============================================================
  # ResultsPoolplayShow
  cerad_game__project__results_poolplay__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Show\ResultsPoolplayShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'

  cerad_game__project__results_poolplay__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Show\ResultsPoolplayShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__results_poolplay__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Show\ResultsPoolplayShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__results_poolplay__show_view:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Show\ResultsPoolplayShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
    arguments:
      - '%cerad_project_pools%'
      
  # ============================================================
  # ResultsPoolplayExport
  cerad_game__project__results_poolplay__export_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Export\ResultsPoolplayExportModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
             
  cerad_game__project__results_poolplay__export_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Export\ResultsPoolplayExportController
      
  cerad_game__project__results_poolplay__export_view:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Poolplay\Export\ResultsPoolplayExportView
    arguments:
      - '%cerad_project_pools%'
      
  # ============================================================
  # ResultsExport
  cerad_game__project__results__export_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Export\ResultsExportModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
             
  cerad_game__project__results__export_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Export\ResultsExportController
      
  cerad_game__project__results__export_view:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Export\ResultsExportView
    arguments:
      - '@cerad_game__project__results__export_xls'
      
  cerad_game__project__results__export_xls:
    class: '%cerad_game__project__results__export_xls__class%'
    
  # ============================================================
  # Results Playoffs Show
  cerad_game__project__results_playoffs__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\ResultsShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
           
  cerad_game__project__results_playoffs__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\ResultsShowController
    calls:
     #- [setRouter,     ['@router']]
     #- [setTemplating, ['@templating']]
      
  cerad_game__project__results_playoffs__show_view:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Playoffs\Show\ResultsPlayoffsShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
    arguments:
      - '%cerad_project_pools%'
      
  # ============================================================
  # Results Sportsmanship Show
  cerad_game__project__results_sportsmanship__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\ResultsShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
           
  cerad_game__project__results_sportsmanship__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\ResultsShowController
    calls:
     #- [setRouter,     ['@router']]
     #- [setTemplating, ['@templating']]
      
  cerad_game__project__results_sportsmanship__show_view:
    class: Cerad\Bundle\GameBundle\Action\Project\Results\Sportsmanship\Show\ResultsSportsmanshipShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
    arguments:
      - '%cerad_project_pools%'
      
