parameters:
  
services:
  
# =======================================================================
# Action: ScheduleGameShow
#
  cerad_game__project__schedule_game__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - 'ScheduleGameShow'
      - false

  cerad_game__project__schedule_game__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Show\ScheduleGameShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__schedule_game__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowController
      
  cerad_game__project__schedule_game__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_game__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_game__export_csv'
      - 'GameSchedule'
      
  cerad_game__project__schedule_game__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_game__export_xls'
      - 'GameSchedule'
      
  cerad_game__project__schedule_game__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Show\ScheduleGameExportCSV
    
  cerad_game__project__schedule_game__export_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Show\ScheduleGameExportXLS
    

# =======================================================================
# Action: ScheduleRefereeShow
#
  cerad_game__project__schedule_referee__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - 'ScheduleRefereeShow'
      - true

  cerad_game__project__schedule_referee__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__schedule_referee__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowController
      
  cerad_game__project__schedule_referee__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_referee__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_csv'
      - 'RefereeSchedule'
      
  cerad_game__project__schedule_referee__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_xls'
      - 'RefereeSchedule'
      
  cerad_game__project__schedule_referee__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeExportCSV
    
  cerad_game__project__schedule_referee__export_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeExportXLS
    
# =======================================================================
# Action: ScheduleTeamShow
#
  cerad_game__project__schedule_team__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - '@cerad_game__team_repository'

  cerad_game__project__schedule_team__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setDispatcher,  ['@event_dispatcher']]
      - [setFormFactory, ['@form.factory']]
             
  cerad_game__project__schedule_team__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_team__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_team__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowViewFile
    arguments:
      - '@cerad_game__project__schedule_team__export_csv'
      
  cerad_game__project__schedule_team__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowViewFile
    arguments:
      - '@cerad_game__project__schedule_team__export_xls'
      
  cerad_game__project__schedule_team__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamExportCSV
    
  cerad_game__project__schedule_team__export_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamExportXLS
    
