parameters:
  
services:
  
# =======================================================================
# Action: ScheduleGameShow
#
  cerad_game__project__schedule_game__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - 'ScheduleGameShow'
      - false

  cerad_game__project__schedule_game__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Show\ScheduleGameShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__schedule_game__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowController
      
  cerad_game__project__schedule_game__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_game__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_game__export_csv'
      - 'GameSchedule'
      
  cerad_game__project__schedule_game__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_game__util_dump_xls'
      - 'ScheduleGame'
      
  cerad_game__project__schedule_game__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Show\ScheduleGameExportCSV
    
  cerad_game__project__schedule_game__util_dump_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Util\ScheduleGameUtilDumpXLS
    arguments:
      - '@cerad_game__transformer'

# =======================================================================
# Action: ScheduleGameImport
#
  cerad_game__project__schedule_game__import_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Import\ScheduleGameImportModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__project__schedule_game__import_xls'
      
  cerad_game__project__schedule_game__import_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Import\ScheduleGameImportFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__schedule_game__import_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Import\ScheduleGameImportController
    calls:
      - [setTemplating, ['@templating']]
              
  cerad_game__project__schedule_game__save_orm:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Util\ScheduleGameUtilSaveORM
    arguments:
      - '@cerad_game__game_repository'
      
  cerad_game__project__schedule_game__import_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Import\ScheduleGameImportFromXLS
    arguments:
      - '@event_dispatcher'
      - '@cerad_game__game_repository'
      - '@cerad_game__transformer'

  cerad_game__project__schedule_game__import_read_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Game\Import\ScheduleGameImportReadXLS
    arguments:
      - '@cerad_game__transformer'
      - '%cerad_project__game_slot_durations%'
      - '@cerad_level__level_repository'
      
# =======================================================================
# Action: ScheduleRefereeShow
#
  cerad_game__project__schedule_referee__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - 'ScheduleRefereeShow'
      - true

  cerad_game__project__schedule_referee__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setFormFactory, ['@form.factory']]
      - [setDispatcher,  ['@event_dispatcher']]
             
  cerad_game__project__schedule_referee__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowController
      
  cerad_game__project__schedule_referee__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_referee__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_csv'
      - 'RefereeSchedule'
      
  cerad_game__project__schedule_referee__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_xls'
      - 'RefereeSchedule'
      
  cerad_game__project__schedule_referee__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeExportCSV
    
  cerad_game__project__schedule_referee__export_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Referee\Show\ScheduleRefereeExportXLS
    
# =======================================================================
# Action: ScheduleTeamShow
#
  cerad_game__project__schedule_team__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - '@cerad_game__team_repository'

  cerad_game__project__schedule_team__show_form_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowFormFactory
    calls:
      - [setRouter,      ['@router']]
      - [setDispatcher,  ['@event_dispatcher']]
      - [setFormFactory, ['@form.factory']]
             
  cerad_game__project__schedule_team__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowController
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_team__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_team__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowViewFile
    arguments:
      - '@cerad_game__project__schedule_team__export_csv'
      
  cerad_game__project__schedule_team__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamShowViewFile
    arguments:
      - '@cerad_game__project__schedule_team__export_xls'
      
  cerad_game__project__schedule_team__export_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamExportCSV
    
  cerad_game__project__schedule_team__export_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\Team\Show\ScheduleTeamExportXLS
    
# =======================================================================
# Action: ScheduleUserShow
#
  cerad_game__project__schedule_user__show_model_factory:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\User\Show\ScheduleUserShowModel
    calls:
      - [setDispatcher,['@event_dispatcher']]
    arguments:
      - '@cerad_game__game_repository'
      - '@cerad_level__level_repository'
      - '@cerad_game__team_repository'

  cerad_game__project__schedule_user__show_controller:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\User\Show\ScheduleUserShowController
      
  cerad_game__project__schedule_user__show_view_html:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowView
    calls:
      - [setRouter,     ['@router']]
      - [setTemplating, ['@templating']]
      
  cerad_game__project__schedule_user__show_view_csv:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_csv'
      
  cerad_game__project__schedule_user__show_view_xls:
    class: Cerad\Bundle\GameBundle\Action\Project\Schedule\ScheduleShowViewFile
    arguments:
      - '@cerad_game__project__schedule_referee__export_xls'
