parameters:
    cerad_game__game_official__assign_slot__workflow__class:
        Cerad\Bundle\GameBundle\Service\GameOfficial\AssignSlot\AssignSlotWorkflow
        
    cerad_game__game_event_listener__class:
        Cerad\Bundle\GameBundle\EventListener\GameEventListener

services:

# =============================================================
# Game Stuff

    cerad_game__entity_manager__doctrine:
        alias: doctrine.orm.games_entity_manager
        
    cerad_game__game_repository__doctrine:
        class:  Cerad\Bundle\GameBundle\Doctrine\EntityRepository\GameRepository
        factory_service: 'cerad_game__entity_manager__doctrine'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\GameBundle\Doctrine\Entity\Game'
        
    cerad_game__game_repository:
        alias: cerad_game__game_repository__doctrine
            
    cerad_game__game_event_listener:
        class: '%cerad_game__game_event_listener__class%'
        calls:
             - [setContainer, ['@service_container']]
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - 'cerad_game__game_repository'
        
    cerad_game__convert__rick_to_yaml:
        class: Cerad\Bundle\GameBundle\Service\GameSchedule\Convert\ConvertRickToYaml
        
    cerad_game__load_games:
        class: Cerad\Bundle\GameBundle\Service\GameSchedule\Load\LoadGames
        arguments:
            - '@cerad_game__game_repository'
        
    # ====================================================
    # Game Officials
    cerad_game__game_official__user_assign_slot__model:
        class: Cerad\Bundle\GameBundle\Controller\GameOfficial\UserAssignSlot\UserAssignSlotModel
        calls:
             - [setDispatcher,['@event_dispatcher']]
        arguments:
            - '@cerad_project.project_current'
            - '@cerad_user__user_person_current'
            - '@cerad_game__game_repository'
            - '@cerad_game__game_official__assign_slot__workflow'
                        
    cerad_game__game_official__user_assign_slot__form_factory:
        class: Cerad\Bundle\GameBundle\Controller\GameOfficial\UserAssignSlot\UserAssignSlotFormFactory
        calls:
             - [setRouter,      ['@router']]
             - [setFormFactory, ['@form.factory']]
        arguments:
            - '@cerad_game__game_official__user_assign_slot__form_type'
            
    cerad_game__game_official__user_assign_slot__controller:
        class: Cerad\Bundle\GameBundle\Controller\GameOfficial\UserAssignSlot\UserAssignSlotController
        calls:
             - [setRouter,     ['@router']]
             - [setTemplating, ['@templating']]

    cerad_game__game_official__user_assign_slot__form_type:
        class: Cerad\Bundle\GameBundle\FormType\GameOfficial\UserAssignSlot\UserAssignSlotFormType
        arguments: 
            - '@cerad_game__game_official__assign_slot__workflow'
        tags:
            - { name: form.type, alias: cerad_game__game_official__user_assign_slot } 
            
    cerad_game__game_official__assign_slot__workflow:
        class: '%cerad_game__game_official__assign_slot__workflow__class%'
        arguments:
            - '%cerad_game__game_official__assign__workflow__file%'

