parameters:

    cerad_project_project_default: AYSONationalGames2014 # CeradTest13
    
    cerad_project_project_files:
        - "%kernel.root_dir%/config/projects/Tests.yml"
        - "%kernel.root_dir%/config/projects/AYSONationalGames2014.yml"
        - "%kernel.root_dir%/config/projects/USSF_AL_HFC_Kicks2013.yml"
          