# =================================================
# Top pages
cerad_tourn_index:
    pattern:  /
    defaults: { _controller: CeradTournBundle:Tourn/Index:index }
    
cerad_tourn_welcome:
    pattern:  /welcome
    defaults: { _controller: CeradTournBundle:Tourn/TournWelcome:welcome }
    
cerad_tourn_home:
    pattern:  /home
    defaults: { _controller: CeradTournBundle:Tourn/TournHome:home }
    
cerad_tourn_contact:
    pattern:  /contact
    defaults: { _controller: CeradTournBundle:Tourn/TournContact:contact }

cerad_tourn_help:
    pattern:  /help
    defaults: { _controller: CeradTournBundle:Tourn/TournHelp:help }

cerad_tourn_test:
    pattern:  /test
    defaults: { _controller: CeradTournBundle:Tourn/TournTest:test }

    
