cerad_api_v1:
    resource: "@CeradApiV1Bundle/Resources/config/routing.yml"
    prefix:   /

cerad_app_cerad:
    resource: "@CeradAppCeradBundle/Resources/config/routing.yml"
    prefix:   /

cerad_tourn_admin:
    resource: "@CeradTournAdminBundle/Resources/config/routing.yml"
    prefix:   /

cerad_game:
    resource: "@CeradGameBundle/Resources/config/routing.yml"
    prefix:   /

# ==================================================
# Tournament Routes
cerad_tourn:
  resource: "@CeradTournBundle/Resources/config/routing.yml"
