cerad_game:
    resource: "@CeradGameBundle/Resources/config/routing.yml"
    prefix:   /

# ==================================================
# Tournament Routes
cerad_tourn:
  resource: "@CeradTournBundle/Resources/config/routing.yml"
