cerad_tourn:
    resource: "@CeradTournBundle/Resources/config/routing.yml"
    prefix:   /

cerad_user:
    resource: "@CeradUserBundle/Resources/config/routing.yml"
    prefix:   /

cerad_person:
    resource: "@CeradPersonBundle/Resources/config/routing.yml"
    prefix:   /

cerad_project:
    resource: "@CeradProjectBundle/Resources/config/routing.yml"
    prefix:   /

