parameters:
#    cerad_level.example.class: Cerad\Bundle\LevelBundle\Example

services:
#    cerad_level.example:
#        class: %cerad_level.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
