# cerad_game_routing

# Update game report
cerad_game__project__game_report__update:
    pattern:  /project/{_project}/game-report/{_game}/update
    defaults:
        _model:      cerad_game__project__game_report__update__model_factory
        _form:       cerad_game__project__game_report__update__form_factory
        _controller: cerad_game__project__game_report__update__controller:action
        _template: '@CeradGame/Project/GameReport/Update/GameReportUpdatePage.html.twig'

# Game Update By Scorer
cerad_game__project__game__update__by_scorer:
    path:  /project/{_project}/game/{_game}/update-by-scorer
    defaults:
        _rolex:       ROLE_SCORER_ADMIN
        _model:      cerad_game__project__game__update__by_scorer__model_factory
        _form:       cerad_game__project__game__update__by_scorer__form_factory
        _controller: cerad_game__project__game__update__by_scorer__controller:updateAction
        _template: '@CeradGame/Project/Game/Update/ByScorer/GameUpdateByScorerIndex.html.twig'
        _redirectx:   cerad_tourn_schedule_list
        
# Game Official (singular) implies only one slot
cerad_game__project__game_official__assign_by_user:
    path:  /project/{_project}/game/{_game}/official/{_game_official}/assign-by-user
    defaults:
        _controller: cerad_game__project__game_official__assign_by_user__controller:assignAction
        _model:      cerad_game__project__game_official__assign_by_user__model_factory
        _form:       cerad_game__project__game_official__assign_by_user__form_factory
        _view:       cerad_game__project__game_official__assign_by_user__view_factory
        _template: '@CeradGame/Project/GameOfficial/AssignByUser/AssignByUserIndex.html.twig'
        _redirect:   cerad_tourn_schedule_official_list
        _role:       ROLE_USER
        _user_person: required

# Game Officials (plural) implies multiple all officials for the game
cerad_game__project__game_officials__assign_by_assignor:
    path:  /project/{_project}/game/{_game}/officials/assign-by-assignor
    defaults:
        _controller: cerad_game__project__game_officials__assign_by_assignor__controller:assignAction
        _model:      cerad_game__project__game_officials__assign_by_assignor__model_factory
        _form:       cerad_game__project__game_officials__assign_by_assignor__form_factory
        _view:       cerad_game__project__game_officials__assign_by_assignor__view_factory
        _template: '@CeradGame/Project/GameOfficials/AssignByAssignor/AssignByAssignorIndex.html.twig'
        _redirect:   cerad_tourn_schedule_official_list
        _role:       ROLE_ASSIGNOR
        
# RefereeSchedule
cerad_game__project__referee_schedule__show:
    path:  /project/{_project}/referee-schedule
    defaults: 
        _controller: cerad_game__project__referee_schedule__show_controller:action
        _model:      cerad_game__project__referee_schedule__show_model_factory
        _form:       cerad_game__project__referee_schedule__show_form_factory
        _template: '@CeradGame\Project\RefereeSchedule\Show\RefereeScheduleShowPage.html.twig'
        
cerad_game__referee_schedule__show:
    path:  /referee-schedule
    defaults: 
        _controller: cerad_game__project__referee_schedule__show_controller:action
        _model:      cerad_game__project__referee_schedule__show_model_factory
        _form:       cerad_game__project__referee_schedule__show_form_factory
        _template: '@CeradGame\Project\RefereeSchedule\Show\RefereeScheduleShowPage.html.twig'
        _project:    ~
