parameters:
#    cerad_tourn_admin.example.class: Cerad\Bundle\TournAdminBundle\Example

services:
#    cerad_tourn_admin.example:
#        class: %cerad_tourn_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
