parameters:
#    cerad_user.example.class: Cerad\Bundle\UserBundle\Example

services:
#    cerad_user.example:
#        class: %cerad_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
