parameters:
#    cerad_tourn.example.class: Cerad\Bundle\TournBundle\Example

services:
#    cerad_tourn.example:
#        class: %cerad_tourn.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
