parameters:
#    cerad_tourn.example.class: Cerad\Bundle\TournBundle\Example

services:
    cerad_tourn.twig_extension:
        class:  Cerad\Bundle\TournBundle\TwigExtension\TournExtension
        arguments:  
            - '@cerad_project.find_default.in_memory'
            - '%cerad_tourn_show_configs%'
        tags:
            - { name: twig.extension }

    cerad_tourn.schedule_official_search.form_type:
        class: Cerad\Bundle\TournBundle\FormType\Schedule\Official\SearchFormType
        tags:
            - { name: form.type, alias: cerad_schedule_official_search }
            
    cerad_tourn.s5games_results:
        class: Cerad\Bundle\TournBundle\Results\S5GamesResults
        arguments:  
            - '@cerad_game.game_repository'

