Cerad\Bundle\PersonBundle\Entity\PersonFed:
    type:  entity
    table: person_feds
    changeTrackingPolicy: NOTIFY
    uniqueConstraints:
        person_fed_role_index:
            columns: fed_role_id, person_id
    
    id:
       id:
           type: integer
           generator: { strategy: AUTO }
                
    manyToOne:
        person:
            targetEntity: Person
            inversedBy:   feds
            
    oneToMany:
                  
       orgs:
           targetEntity: PersonFedOrg
           mappedBy:     fed
           indexBy:      role
           cascade:      ['all']
            
       certs:
           targetEntity: PersonFedCert
           mappedBy:     fed
           indexBy:      role
           cascade:      ['all']
                        
    fields:
      
        fedId:
            column:   fed_id
            type:     string
            length:   40
            nullable: false
            unique:   true
            
        fedRoleId:
            column:   fed_role_id
            type:     string
            length:   40
            nullable: false
                                    
        status:
            type:     string
            length:   20
            nullable: false
            
        verified:
            type:     string
            length:   20
            nullable: true
    