Cerad\Bundle\PersonBundle\Entity\PersonFed:
    type:  entity
    table: person_feds
    changeTrackingPolicy: NOTIFY
    
    id:
       id:
           type:   string
           length: 40
           generator: { strategy: NONE }
                
    manyToOne:
        person:
            targetEntity: Person
            inversedBy:   feds
            
    oneToMany:
                  
       orgs:
           targetEntity: PersonFedOrg
           mappedBy:     fed
           indexBy:      role
           cascade:      ['all']
            
       certs:
           targetEntity: PersonFedCert
           mappedBy:     fed
           indexBy:      role
           cascade:      ['all']
                        
    fields:
      
        fedRoleId:
            column:   fed_role_id
            type:     string
            length:   40
            nullable: false
                                    
        status:
            type:     string
            length:   20
            nullable: false
            
        verified:
            type:     string
            length:   20
            nullable: true
    