parameters:
#    cerad_project.example.class: Cerad\Bundle\ProjectBundle\Example

services:

    cerad_project.repository.in_memory:
        class:  Cerad\Bundle\ProjectBundle\InMemory\ProjectRepository
        arguments:  
            - '%cerad_project_project_files%'

    cerad_project.find_default.in_memory:
        class:  Cerad\Bundle\ProjectBundle\InMemory\ProjectFind
        arguments:  
            - '@cerad_project.repository.in_memory'
            - '%cerad_project_project_default%'
            
    cerad_project.project_repository:
        alias: cerad_project.repository.in_memory
