parameters:
#    cerad_project.example.class: Cerad\Bundle\ProjectBundle\Example

services:
#    cerad_project.example:
#        class: %cerad_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
