    
cerad_person__project__person__teams__show:
    path:  /project/{_project}/person/{_person}/teams/show
    defaults: 
        _controller: cerad_person__project__person__teams__show_controller:action
        _model:      cerad_person__project__person__teams__show_model_factory
       #_form:       cerad_person__project__person__teams__show_form_factory
        _template: '@CeradPerson\Project\Person\Teams\Show\TeamsShowTwigPage.html.twig'
