parameters:
#    cerad_person.example.class: Cerad\Bundle\PersonBundle\Example

services:
#    cerad_person.example:
#        class: %cerad_person.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
