# PersonBundle Services
parameters:
    # cerad_person.example.class: Cerad\Bundle\PersonBundle\Example

    # Did not work for alias
    cerad_person.entity_manager.doctrine.service: doctrine.orm.default_entity_manager

services:
#    cerad_person.example:
#        class: %cerad_person.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    cerad_person.entity_manager.doctrine:
        alias: doctrine.orm.default_entity_manager

    cerad_person.repository.doctrine:
        class:  Cerad\Bundle\PersonBundle\Repository\PersonRepositoryDoctrine
        factory_service: 'cerad_person.entity_manager.doctrine'
        factory_method:  'getRepository'
        arguments:  
            - 'Cerad\Bundle\PersonBundle\Entity\Person'

# ====================================================
# Data transformers
    cerad_person.aysor_id.data_transformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\RegionIdTransformer
                        
    cerad_person.aysov_id.data_transformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\VolunteerIdTransformer
        
    cerad_person.aysov_id.data_transformer.fake:
        class: Cerad\Bundle\PersonBundle\DataTransformer\AYSO\VolunteerIdTransformer
        arguments: [true]
        
    cerad_person.ussfs_id.data_transformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\USSF\StateIdTransformer
                        
    cerad_person.ussfc_id.data_transformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\USSF\ContractorIdTransformer
        
    cerad_person.ussfc_id.data_transformer.fake:
        class: Cerad\Bundle\PersonBundle\DataTransformer\USSF\ContractorIdTransformer
        arguments: [true]
        
    cerad_person.phone.datatransformer:
        class: Cerad\Bundle\PersonBundle\DataTransformer\PhoneTransformer
