parameters:
#    cerad_core.example.class: Cerad\Bundle\CoreBundle\Example

services:
#    cerad_core.example:
#        class: %cerad_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
