parameters:
#    cerad_api_v1.example.class: Cerad\Bundle\ApiV1Bundle\Example

services:
#    cerad_api_v1.example:
#        class: %cerad_api_v1.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
