
services:
    cerad_api_v1.person.controller:
        class: Cerad\Bundle\ApiV1Bundle\Controller\PersonController
        arguments: 
            - '@cerad_person.person_repository'
            
    cerad_api_v1.persons.controller:
        class: Cerad\Bundle\ApiV1Bundle\Controller\PersonsController
        arguments: 
            - '@cerad_person.person_repository'
