parameters:
#    cerad_app_cerad.example.class: Cerad\Bundle\AppCeradBundle\Example

services:

    cerad_app_cerad.persons_s1games.export_xml:
        class: Cerad\Bundle\AppCeradBundle\Services\Persons\Persons01ExportXML
        arguments:
            - '@doctrine.dbal.s1games_connection'
            
    cerad_app_cerad.persons.export_xml:
        class: Cerad\Bundle\AppCeradBundle\Services\Persons\Persons01ExportXML
        arguments:
            - '@doctrine.dbal.default_connection'
            
    cerad_app_cerad.persons.import_xml:
        class: Cerad\Bundle\AppCeradBundle\Services\Persons\PersonsImportXML
        arguments:
            - '@doctrine.dbal.default_connection'
            
    cerad_app_cerad.persons.import_xml02:
        class: Cerad\Bundle\AppCeradBundle\Services\Persons\PersonsImportXML02
        arguments:
            - '@doctrine.dbal.default_connection'
            
    # ======================================================
    # Feds
    cerad_app_cerad.feds.export01_yaml:
        class: Cerad\Bundle\AppCeradBundle\Services\Feds\FedsExport01YAML
        arguments:
            - '@doctrine.dbal.s1games_connection'
            
    cerad_app_cerad.feds.import01_yaml:
        class: Cerad\Bundle\AppCeradBundle\Services\Feds\FedsImport01YAML
        arguments:
            - '@doctrine.dbal.default_connection'
